project:
  type: website
  output-dir: docs

website:
  title: "SIMOCUTE - Mesa de Monitoreo por Puntos"
  image: img/logo-mmpp.png
  favicon: img/rwds-favicon.png
  site-url: https://mesa-monitoreo-puntos.github.io/
  repo-url: https://github.com/mesa-monitoreo-puntos/mesa-monitoreo-puntos.github.io
  navbar:
    background: "#f0eeeb"
    logo: img/logo-mmpp.png
    logo-alt: "SIMOCUTE - Mesa de Monitoreo por Puntos"
    title: false
    collapse-below: lg
    right:
      - evm/index.qmd
      - evm-casos-estudio/index.qmd
        
  page-navigation: true

format:
  html:
    lang: es
    code-link: true
    theme: [lux, mmpp.scss]
    css: mmpp.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px