---
title: "Mesa de Monitoreo por Puntos"
toc-title: "Contenidos"
---

Este es el sitio web de la Mesa de Monitoreo por puntos del Sistema de Monitoreo y Cobertura de la Tierra y Ecosistemas (SIMOCUTE).

## **¿Qué es el SIMOCUTE?**

El Sistema Nacional de Monitoreo de Cobertura y Uso de la Tierra y Ecosistemas (**SIMOCUTE**) es la plataforma oficial de coordinación, vinculación e integración institucional y sectorial del Estado costarricense para facilitar la gestión y distribución del conocimiento e información en materia de cobertura y uso de la tierra y ecosistemas (CENIGA: 2020). 

**Objetivo general**: Conocer el estado actual y los cambios de la cobertura y uso de la tierra, así como de los ecosistemas de Costa Rica, proporcionando información periódica de alta calidad, que permita evaluar el estado el estado de los recursos del medio ambiente. 

El SIMOCUTE está diseñado para responder a tres preguntas específicas: ¿qué hay?, la cual se refiere a las categorías de uso, cobertura y escosistemas presentes en el territorio; ¿dónde está?, que hace referencia a la ubicación geográfica de los elementos definidos en la primera pregunta; y ¿cuánto hay? que indica la cuantificación de los recursos según su composición de cada una de dichas categorías (CENIGA: 2020).

El SIMOCUTE está conformado en su gobernanza por el Comité Ejecutivo, la Unidad Coordinadora, el Grupo Consultivo de Mesas Técnicas y las Mesas Técnicas, las cuales constituyen la base de todo el sistema, desde donde se generan las discusiones y recomendaciones técnicas para el desarrollo del Sistema, así como se gestionan y elaboran productos que pueden ser utilizados por las instituciones.  

## ¿Qué es la Mesa de Monitoreo por Puntos?

La Mesa de Monitreo por Puntos se creó en el año 2017 y fue la primera en ser creada. Tiene como objetivo "definir un proceso que apoye a las instituciones en el conocimiento del estado actual y los cambios en el uso y cobertura de la tierra, mediante un sistema de monitoreo visual de puntos, que permita disponer de datos frecuentes para la toma de decisiones y compromisos institucionales". 

La Mesa técnica es coordinada por el Instituto Meteorológico Nacional y está conformada por representantes de instituciones del MINAE (CENIGA, IMN, FONAFIFO, Secretaría REDD+, SINAC), del MAG (INTA, SFE, SEPSA), otras instancias (BANCO CENTRAL, ICE, IGN, INEC), de la academia (PRIAS-CENAT, TEC, UCR, UNA, CATIE) y cooperantes (FAO, SilvaCarbon, PNUD). 

Esta Mesa ha tenido desde el 2017 sesiones de trabajo en donde se han desarrollado lo diferentes componentes de la metodología de Evaluación Visual Multitemporal (EVM). Además, se han elaborado varios estudios piloto en el contexto de la Mesa para tomar decisiones acerca de temas específicos de la metodología. 

La información resultante de esta metodología puede servir como insumo para los reportes solicitados por diferentes iniciativas, tales como el Programa REDD+, las Comunicaciones Nacionales e Informes Bienales de Actualización requeridos por la Convención Marco de las Naciones Unidas sobre el Cambio Climático (CMNUCC) y las Acciones de Mitigación Nacionalmente Apropiadas (NAMA, por sus siglas en inglés), así como el Inventario Nacional Forestal, cuentas ambientales, la academia, entre otros (Calvo y Hamilton: 2020).

## Objetivo general

El objetivo definido para la Mesa desde su conformación es el siguiente: "Definir un proceso que apoye a las instituciones en el conocimiento del estado actual y los cambios en el uso y cobertura de la tierra, mediante un sistema de monitoreo visual de puntos, que permita disponer de datos frecuentes para la toma de decisiones y compromisos institucionales"

Para lograr esto se definieron los siguientes objetivos:

### Objetivos específicos

1. Construir una metodología base de interpretación visual de puntos de muestreo para el monitoreo del uso y cobertura de la tierra.

2. Preparar un documento técnico que detalle la metodología base de interpretación visual de puntos de muestreo para su revisión.

3. Coordinar la realización de estudios piloto para la validación de la metodología base de interpretación visual de puntos de muestreo.

4. Elaborar un protocolo con las pautas para la implementación y evaluación de la metodología base de interpretación visual de puntos de muestreo.

5. Entregar al coordinador del SIMOCUTE el documento técnico y el protocolo de implementación y evaluación de la metodología base de interpretación visual de puntos de muestreo para su respectiva.

=======
---
title: "Mesa de Monitoreo por Puntos"
toc-title: "Contenidos"
---

Este es el sitio web de la Mesa de Monitoreo por puntos del Sistema de Monitoreo y Cobertura de la Tierra y Ecosistemas (SIMOCUTE).

## ¿Qué es el SIMOCUTE?

El Sistema Nacional de Monitoreo de Cobertura y Uso de la Tierra y Ecosistemas (**SIMOCUTE**) es la plataforma oficial de coordinación, vinculación e integración institucional y sectorial del Estado costarricense para facilitar la gestión y distribución del conocimiento e información en materia de cobertura y uso de la tierra y ecosistemas (CENIGA: 2020). 

**Objetivo general**: Conocer el estado actual y los cambios de la cobertura y uso de la tierra, así como de los ecosistemas de Costa Rica, proporcionando información periódica de alta calidad, que permita evaluar el estado el estado de los recursos del medio ambiente. 

El SIMOCUTE está diseñado para responder a tres preguntas específicas: ¿qué hay?, la cual se refiere a las categorías de uso, cobertura y escosistemas presentes en el territorio; ¿dónde está?, que hace referencia a la ubicación geográfica de los elementos definidos en la primera pregunta; y ¿cuánto hay? que indica la cuantificación de los recursos según su composición de cada una de dichas categorías (CENIGA: 2020).

El SIMOCUTE está conformado en su gobernanza por el Comité Ejecutivo, la Unidad Coordinadora, el Grupo Consultivo de Mesas Técnicas y las Mesas Técnicas, las cuales constituyen la base de todo el sistema, desde donde se generan las discusiones y recomendaciones técnicas para el desarrollo del Sistema, así como se gestionan y elaboran productos que pueden ser utilizados por las instituciones.  

## ¿Qué es la Mesa de Monitoreo por Puntos?

La Mesa de Monitreo por Puntos se creó en el año 2017 y fue la primera en ser creada. Tiene como objetivo "definir un proceso que apoye a las instituciones en el conocimiento del estado actual y los cambios en el uso y cobertura de la tierra, mediante un sistema de monitoreo visual de puntos, que permita disponer de datos frecuentes para la toma de decisiones y compromisos institucionales". 

La Mesa técnica es coordinada por el Instituto Meteorológico Nacional y está conformada por representantes de instituciones del MINAE (CENIGA, IMN, FONAFIFO, Secretaría REDD+, SINAC), del MAG (INTA, SFE, SEPSA), otras instancias (BANCO CENTRAL, ICE, IGN, INEC), de la academia (PRIAS-CENAT, TEC, UCR, UNA, CATIE) y cooperantes (FAO, SilvaCarbon, PNUD). 

Esta Mesa ha tenido desde el 2017 sesiones de trabajo en donde se han desarrollado lo diferentes componentes de la metodología de Evaluación Visual Multitemporal (EVM). Además, se han elaborado varios estudios piloto en el contexto de la Mesa para tomar decisiones acerca de temas específicos de la metodología. 

La información resultante de esta metodología puede servir como insumo para los reportes solicitados por diferentes iniciativas, tales como el Programa REDD+, las Comunicaciones Nacionales e Informes Bienales de Actualización requeridos por la Convención Marco de las Naciones Unidas sobre el Cambio Climático (CMNUCC) y las Acciones de Mitigación Nacionalmente Apropiadas (NAMA, por sus siglas en inglés), así como el Inventario Nacional Forestal, cuentas ambientales, la academia, entre otros (Calvo y Hamilton: 2020).

## Objetivo general

El objetivo definido para la Mesa desde su conformación es el siguiente: "Definir un proceso que apoye a las instituciones en el conocimiento del estado actual y los cambios en el uso y cobertura de la tierra, mediante un sistema de monitoreo visual de puntos, que permita disponer de datos frecuentes para la toma de decisiones y compromisos institucionales"

Para lograr esto se definieron los siguientes objetivos:

### Objetivos específicos

1. Construir una metodología base de interpretación visual de puntos de muestreo para el monitoreo del uso y cobertura de la tierra.

2. Preparar un documento técnico que detalle la metodología base de interpretación visual de puntos de muestreo para su revisión.

3. Coordinar la realización de estudios piloto para la validación de la metodología base de interpretación visual de puntos de muestreo.

4. Elaborar un protocolo con las pautas para la implementación y evaluación de la metodología base de interpretación visual de puntos de muestreo.

5. Entregar al coordinador del SIMOCUTE el documento técnico y el protocolo de implementación y evaluación de la metodología base de interpretación visual de puntos de muestreo para su respectiva.
