---
title: "Otros recursos"
---

1.  Malla de Puntos del SIMOCUTE

La Malla de Puntos N1 del SIMOCUTE y sus densificaciones N2 y N3

Las mallas de puntos son un arreglo que forma hexágonos de 7 puntos que surgen de la necesidad de geolocalizar ubicaciones de forma sistemática que ayuden al monitoreo de los usos y coberturas de la tierra en Costa Rica. La malla principal a partir de las cuales surgen los niveles de mayor densidad de puntos proviene del arreglo sistemático del Inventario Forestal Nacional de 2013-2014 que lideró SINAC. La diferencia en distancia de los puntos de la malla original es de 2402.81m, reduciéndose a la mitad conforme se intensifican las mallas.

[Método de construción y densificación de las mallas](documents/XXX.pdf)\

2.  Sistema de Clasificación del SIMOCUTE Versión 2.1

El objetivo general del SIMOCUTE es dar a conocer el estado actual y los cambios de la cobertura y uso de la tierra, así como de los ecosistemas, y proporcionar información periódica que permita evaluar el estado de los recursos del medio ambiente. Para cumplir esta meta se requiere, entre otras cosas, de la estandarización de metodologías, protocolos y otras herramientas para monitorear la cobertura y el uso de la tierra y los ecosistemas. Se ha identificado que para cumplir con los objetivos propuestos para el SIMOCUTE se requiere de un sistema de clasificación de uso y cobertura de la tierra (SICUCT) que permita la operación de un sistema robusto y transparente de monitoreo. Este sistema de clasificación es la agrupación de entidades similares en grupos o clases basadas en características comunes para la cobertura y uso de la tierra, con las definiciones clave asociadas.

La clasificación es uno de los componentes más importantes del SIMOCUTE. Responde a la pregunta "¿qué es?" y determina las definiciones y claves asociadas para realizar los procesos de monitoreo. La labor consiste en la construcción y mejora continua de un sistema de clasificación armonizado del territorio costarricense.

Los sistemas de clasificación del SIMOCUTE cumplen las siguientes características:

-   Exhaustivo
-   Mutualmente Excluyente
-   Jerárquico
-   Robusto
-   Transparente
-   Dinámico

El uso de la tierra se define como "descripción del uso funcional de un sitio, tal y como elementos biofísicos y culturales". Por ejemplo, pastos, plantaciones, forestales, café, bosques, etc. El uso de la tierra requiere una perspectiva humana, la interpretación de las actividades, tiene una superficie mínima asociada y en ocasiones se requiere observación in situ.

La cobertura de la tierra, corresponde a la cubierta biofísica presente en un sitio con sus elementos naturales y antrópicos. En este caso no requiere de análisis de contexto o inferencia del entorno, y no tiene un área mínima asociada a ella.

[Sistema de Clasificación de Cobertura y Uso de la tierra del SIMOCUTE](documents/XXX.pdf)\

3.  Página del SIMOCUTE

El SIMOCUTE es la plataforma oficial de coordinación, vinculación e integración institucional y sectorial del Estado costarricense, para facilitar la gestión y distribución del conocimiento e información en materia de cobertura y uso de la tierra y ecosistemas, integrado al Sistema Nacional de Información Ambiental (SINIA) del MINAE y vinculado oficialmente con el Sistema Nacional de Información Territorial (SNIT) del IGN del Registro Nacional.

El objetivo general del SIMOCUTE es dar a conocer el estado actual y los cambios de la cobertura y uso de la tierra, así como de los ecosistemas mediante el monitoreo, para proporcionar información periódica que permita evaluar el estado de los recursos del ambiente. Lo anterior para facilitar la toma de decisiones políticas informadas para promover el uso racional de la tierra y mantener la calidad e integridad de los ecosistemas y el ambiente para las generaciones futuras, así como para responder a compromisos nacionales e internacionales de información

Artículos 2 y 5 del Decreto Ejecutivo N° 42886-MINAE-MAG-JP

[Link a la página del SIMOCUTE](https://https://simocute.go.cr/home)\

4.  Link a manuales y recursos de R y Rstudio

R es un lenguaje de programación enfocado en análisis estadístico. Es ampliamente utilizado en diversas áreas de investigación, entre las que pueden mencionarse ciencia de datos (data science), big data y aprendizaje automático (machine learning). Fue creado por Ross Ihaka y Robert Gentleman en la Universidad de Auckland, Nueva Zelanda, en 1993.

R es un proyecto de software libre que se comparte mediante una licencia GNU General Public Licence (GNU GPL). Esta característica permite que la funcionalidad original de R pueda ser ampliada mediante bibliotecas o paquetes desarrollados por la comunidad de programadores.

Para programar en R, puede utilizarse una interfaz de línea de comandos, editores de texto (ej. Visual Studio Code, Vim) y también ambientes de desarrollo integrados (IDE, integrated development environment) como Jupyter o RStudio.

RStudio es un entorno de desarrollo integrado (IDE) para R y Python. Incluye una consola, un editor de resaltado de sintaxis que admite la ejecución directa de código y herramientas para el trazado, el historial, la depuración y la gestión del espacio de trabajo. RStudio está disponible en ediciones comerciales y de código abierto y se ejecuta en el escritorio (Windows, Mac y Linux).

[Link a la página de Capacitación del SIMOCUTE](https://mesa-monitoreo-puntos.github.io/capacitacion/)\
[Link a la página de RStudio](https://posit.co/products/open-source/rstudio/)\

5.  Link a páginas de descarga de CEO y CED

Open Foris es un conjunto de herramientas de software gratuitas y de código abierto que facilita la recopilación, el análisis y la generación de informes de datos de manera flexible y eficiente. https://openforis.org/

Entre las herramientas desarrolladas por Open Foris, se encuentra Collect Earth que permite la recopilación de datos a través de imágenes satelitales de alta y muy alta resolución para una amplia variedad de propósitos, que incluyen:

Apoyar inventarios forestales nacionales de varias fases Evaluaciones de uso de la tierra, cambio de uso de la tierra y silvicultura (UTCUTS) Seguimiento de terrenos agrícolas y zonas urbanas Validación de mapas existentes Recopilación de datos socioeconómicos espacialmente explícitos Cuantificación de la deforestación, la reforestación y la desertificación.

[Link CEO](https://www.collect.earth/)\
[Link CED](https://openforis.org/tools/collect-earth/)\

6.  Link a página de descarga de QGIS

QGIS (anteriormente llamado también Quantum GIS) es un Sistema de Información Geográfica (SIG) de software libre y de código abierto para plataformas GNU/Linux, Unix, Mac OS, Microsoft Windows y Android.2 Fue uno de los primeros ocho proyectos de la Fundación OSGeo y en 2008 oficialmente superó la fase de incubación. Permite manejar formatos raster y vectoriales a través de la biblioteca GDAL (GADL/OGR), así como bases de datos. Algunas de sus características son:

Soporte para la extensión espacial de PostgreSQL, PostGIS. Manejo de archivos vectoriales Shapefile, ArcInfo coverages, MapInfo, GRASS GIS, DXF, etc. Soporte para un importante número de tipos de archivos ráster (GRASS GIS, GeoTIFF, TIFF, JPG, etc.)

Una de sus mayores ventajas es la posibilidad de usar Quantum GIS como GUI (Interfaz gráfica de usuario) del SIG GRASS, utilizando toda la potencia de análisis de este último en un entorno de trabajo más amigable. QGIS está desarrollado en C++, usando la biblioteca Qt para su Interfaz gráfica de usuario.

https://es.wikipedia.org/wiki/QGIS 20/02/2023

[Link de descarga QGIS](https://qgis.org/es/site/forusers/download.html)\
