---
pagetitle: Evaluación Visual Multitemporal | Mesa de Monitoreo por Puntos
title: Evaluación Visual Multitemporal
search: false  
listing:
  contents:
  - posts
  - "!index.qmd"
  fields: ["image", "title", "subtitle"]
  sort: "date"
  type: grid
  categories: false
  sort-ui: false
  filter-ui: false
  page-size: 30
  feed: true
---

## Introducción
La Evaluación Visual Multitemporal (EVM), también conocida como "Sistema de Monitoreo por Puntos (SMPP)", es una metodología que pretende proporcionar información consistente y periódica acerca de la composición de la cobertura o uso de la tierra, tanto a nivel nacional como regional y local, así como los cambios ocurridos en ambas propiedades del paisaje, entre intervalos determinados de tiempo (Calvo y Hamilton: 2020; https://www.ambientico.una.ac.cr/wp-content/uploads/tainacan-items/5/30672/273_51-56.pdf).

El diseño de la EVM ha estado a cargo de un grupo de expertos de las instituciones que conforman la Mesa Técnica sobre Estimación de Cambios en la Superficie de la Tierra por Puntos (Monitoreo por Puntos), con la guía del Servicio Forestal de los Estados Unidos (USFS) y el programa SilvaCarbon (Calvo y Hamilton: 2020; https://www.ambientico.una.ac.cr/wp-content/uploads/tainacan-items/5/30672/273_51-56.pdf).

La EVM consiste en un muestreo directo de todas las tierras a través de interpretación visual de imágenes de alta resolución, para cuantificar las áreas de cada cobertura y uso de la tierra, los cambios y el nivel de incertidumbre asociado. La metodología consiste en diseñar una grilla sistemática de puntos (que puede ser de 3 x 3, 5 x 5 puntos o más, según la necesidad y recursos) sobre parcelas predefinidas (ver información de las Mallas de SIMOCUTE en el componente 2 de la metodología), visualizándolas sobre imágenes de alta resolución. Un analista con experiencia en el campo revisa los puntos de la grilla e interpreta la cobertura o el uso de la tierra de cada uno (Calvo y Hamilton: 2020; https://www.ambientico.una.ac.cr/wp-content/uploads/tainacan-items/5/30672/273_51-56.pdf). 

## Determinación de la necesidad
El primer paso para la implementación de una EVM es determinar la necesidad que se busca solventar con la información estimada acerca del uso y cobertura de la tierra, ecosistemas, y sus cambios asociados. Este paso es fundamental porque determinará el abordaje metodológico del estudio en lo que se refiere a la escala espacial y temporal, nivel de detalle de la información que se quiere recopilar, el nivel apropiado en el sistema de clasificación y en el nivel de la malla de puntos (parcelas) que se usará para realizar la interpretación, el nivel de incertidumbre aceptable, entre otros. Asimismo, la elaboración de la necesidad debe ir acompañada por un análisis preliminar de los recursos de los que se dispone, ya sean económicos, intelectuales, de personal, así como el tiempo del que se dispone para completar el estudio. 
En este sentido, este primer paso debe responder a las preguntas: ¿Cuál el problema o necesidad que se quiere abordar y requiere para su resolución datos sobre uso de la tierra, cobertura de la tierra y/o ecosistemas? ¿Quiénes son las personas, instituciones, organismos o entes interesados en los resultados del estudio? ¿Cuáles son los recursos que se pueden destinar al estudio? ¿Qué arreglos debo gestionar para poner en marcha el proyecto de EVM? entre otras.

## Componentes
Es esta sección se presentan los pasos a seguir, de acuerdo con cada componente de la metodología, para implementar un proyecto de EVM.